module.exports = {
  "rules": {
    "indent": [2, 2, {"SwitchCase": 1}],
    "quotes": [2, "single"],
    "linebreak-style": [2, "unix"],
    "semi": [2, "always"],
    "no-console": 0,
    "curly": 2,
    "eqeqeq": [2, "smart"],
    "no-alert": 2,
    "no-multi-spaces": 2,
    "no-multi-str": 2,
    "no-new-wrappers": 2,
    "no-new-func": 2,
    "no-new": 2,
    "no-script-url": 2,
    "yoda": 2,
    "no-unused-vars": 2,
    "global-require": 2,
    //"callback-return": [2, ["callback", "cb", "next"]],
    "array-bracket-spacing": [2, "never"],
    "brace-style": [2, "1tbs", { "allowSingleLine": false }],
    "camelcase": [2, {"properties": "always"}],
    "comma-spacing": [2, {"before": false, "after": true}],
    "comma-style": [2, "last"],
    "computed-property-spacing": [2, "never"],
    "consistent-this": [2, "self"],
    "eol-last": 2,
    //"func-names": 2,
    //"func-style": [2, "expression"],
    "key-spacing": [2, {"beforeColon": false, "afterColon": true}],
    "no-array-constructor": 2,
    "no-spaced-func": 2,
    "no-trailing-spaces": 2,
    //"space-after-keywords": 2,
    //"keyword-spacing": [2, {"before": true, "after": false}],
    //"max-len": [2, 80, 4],
    "no-bitwise": 2
  },
  "env": {
    "node": true,
    "browser": true,
    "amd": true,
    "mocha": true,
    "jquery": true,
    "mongo": true
  },
  "globals": {
    "AV": true
  },
  "extends": "eslint:recommended"
}
